# Build settings
[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "netlify/functions"

# API redirects - these must come BEFORE the catch-all redirect
# Specific API endpoint redirects
[[redirects]]
  from = "/api/images/upload"
  to = "/.netlify/functions/images-upload"
  status = 200
  force = true

[[redirects]]
  from = "/api/measurements/:id/metadata"
  to = "/.netlify/functions/update-metadata/:id"
  status = 200
  force = true

[[redirects]]
  from = "/api/angle-data"
  to = "/.netlify/functions/angle-data"
  status = 200
  force = true

[[redirects]]
  from = "/api/latest-angle"
  to = "/.netlify/functions/latest-angle"
  status = 200
  force = true

[[redirects]]
  from = "/api/images/:hashKey"
  to = "/.netlify/functions/images"
  status = 200
  force = true

# Default API redirect for any remaining /api routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true  # Forces this redirect to always happen even if a file exists

# SPA redirect for React router - must be LAST
# This is a catch-all for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
