# Build settings
[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "netlify/functions"

# Use esbuild with external modules
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp", "@techstark/opencv-js"]

# Environment variable settings
[build.environment]
  NODE_VERSION = "18.18.0"
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"
  NODE_OPTIONS = "--no-warnings"

# API redirects - these must come BEFORE the catch-all redirect
# Specific API endpoint redirects
[[redirects]]
  from = "/api/user"
  to = "/.netlify/functions/user/user" # Path to the standalone user function
  status = 200
  force = true

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/login/login" # Path to the standalone login function
  status = 200
  force = true

[[redirects]]
  from = "/api/images/upload"
  to = "/.netlify/functions/images-upload"
  status = 200
  force = true

[[redirects]]
  from = "/api/angle-data"
  to = "/.netlify/functions/angle-data"
  status = 200
  force = true

[[redirects]]
  from = "/api/latest-angle"
  to = "/.netlify/functions/latest-angle"
  status = 200
  force = true

[[redirects]]
  from = "/api/images/:hashKey/original"
  to = "/.netlify/functions/images"
  status = 200
  force = true

[[redirects]]
  from = "/api/images/:hashKey/medium"
  to = "/.netlify/functions/images"
  status = 200
  force = true

[[redirects]]
  from = "/api/images/:hashKey"
  to = "/.netlify/functions/images"
  status = 200
  force = true

[[redirects]]
  from = "/api/thumbnails/:hashKey"
  to = "/.netlify/functions/thumbnails"
  status = 200
  force = true

# Default API redirect for any remaining /api routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true  # Forces this redirect to always happen even if a file exists

# SPA redirect for React router - must be LAST
# This is a catch-all for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
